In [165]:
import numpy as np


In [166]:
data = np.load('monthdata.npz')
totals = data['totals']
counts = data['counts']

In [167]:
sum = np.sum(totals, axis=1)

In [168]:
cityLowest = np.argmin(sum)

In [169]:
print(cityLowest)

8

In [170]:
totalPrecipitation = np.sum(totals, axis=0)

In [171]:
totalObservations = np.sum(counts, axis=0)

In [172]:
averagePrecipitation = totalPrecipitation / totalObservations


In [173]:
print(averagePrecipitation)


array([ 27.77978339,  30.42629482,  29.41007194,  17.96654275,
        21.34456929,  20.69498069,  24.97718631,  19.85661765,
        24.06563707,  44.68441065,  34.61568627,  32.36679537])

In [174]:
countSum = np.sum(counts, axis=1)

In [175]:
cityPrecipitation = sum/countSum

In [176]:
print(cityPrecipitation)

array([ 47.77859779,  14.33333333,  39.91232877,  41.44505495,
        23.4099723 ,  23.68144044,  17.52197802,  36.52222222,   6.15426997])

In [177]:
quarters = np.reshape(totals, (9,4,3))

In [178]:
quartersSum = np.sum(quarters, axis=2)

In [179]:
print(quartersSum)

array([[5450, 1408, 1466, 4624],
       [ 189, 1339, 3148,  527],
       [3120, 3357, 3386, 4705],
       [4416, 3321, 2024, 5325],
       [2024, 1498, 1721, 3208],
       [1786, 1809, 2557, 2397],
       [1583, 1296, 1729, 1770],
       [4602, 1340, 1250, 5956],
       [ 338,  524,  922,  450]], dtype=uint64)